export const selectSelectedMonth = state => state.monthWater.selectedMonth;
export const selectIsCurrentMonth = state => state.monthWater.isCurrentMonth;
export const selectDaysInMonth = state => state.monthWater.daysInMonth;
export const selectSelectedDay = state => state.monthWater.selectedDay;
export const selectIsModalOpen = state => state.monthWater.isModalOpen;
export const selectSelectedDayData = state => state.monthWater.selectedDayData;
export const selectLoadingMonth = state => state.monthWater.isLoadingMonth;
export const selectLoadingDay = state => state.monthWater.isLoadingDay;
export const selectError = state => state.monthWater.error;
